[pytest]
# Adding the current directory to the Python path so that pytest can find the modules to test.
pythonpath = .
testpaths = tests
# asyncio_mode = "auto" automatically detects async test functions and applies the asyncio marker
asyncio_mode = auto
# asyncio_default_fixture_loop_scope = "function" ensures each test function gets its own event loop
asyncio_default_fixture_loop_scope = function
